version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./docker/localstack:/var/lib/localstack"

  mlflow:
    image: bitnami/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - "./mlruns:/opt/bitnami/mlflow/mlruns"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/opt/bitnami/mlflow/mlruns
